### ISSUE TITLE
PhishDetect node -> MISP instance

### ISSUE THREAD

**Issue by mfc** [phishdetect/phishdetect-node#5]
making a ticket to track the ability of a PhishDetect node to push to a configured MISP instance. work on it likely to come from CIRCL team early next year

**Comment by botherder** [comment]
Thank you for opening this ticket.

In order to keep the Node a light and lean service, I do not intend to integrate MISP support directly into PhishDetect Node. I would suggest the two services to be bridged using a middleware Python script that takes care of communicating with the two separate API servers. Perhaps such script could go into https://github.com/phishdetect/phishdetect-utils/.

**Comment by mfc** [comment]
sounds good, closing this ticket and created https://github.com/phishdetect/phishdetect-utils/issues/1
